name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images latest
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: serverfrog/gocrunchqueue:latest
    - name: Build and push Docker images version
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: serverfrog/gocrunchqueue:$(date +%s)
